name 'tal_nginx'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures tal_nginx'
long_description 'Installs/Configures tal_nginx'
version '0.1.0'
